# Stage 1: Compile and Build angular codebase
# Use official node image as the base image
FROM node:latest as build
# Set the working directory
WORKDIR /app
COPY package.json /app/
# Install all the dependencies
RUN npm install
# Add the source code to app
COPY . /app/
# Generate the build of the application
RUN npm run build --prod
# Stage 2: Serve app with nginx server
# Use official nginx image as the base image
FROM nginx:latest
# Copy the build output to replace the default nginx contents.
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/myapp /usr/share/nginx/html
# Expose port 4200
ENV port=4200
EXPOSE ${port}